### PR TITLE
Add bucklescript 7.2.0 support

### PR DESCRIPTION
**Pull request by Coobaha**

### CODE REVIEW

**Comment by Coobaha** [comment]
Fixes issue caused by https://github.com/BuckleScript/bucklescript/pull/4170
@ELLIOTTCABLE

**Comment by ozanvos** [comment]
Alternatively you can change line 11 to `var bsc_executable = require.resolve("bs-platform/bsc")`, and call the platform independent launcher.

**Comment by Coobaha** [comment]
@ELLIOTTCABLE  ping

**Comment by ELLIOTTCABLE** [comment]
Merged and published in [v44.1.2](/ELLIOTTCABLE/bs-deriving/releases/tag/v44.1.2). (=

**Pull request closed without merging**
